name: KubeStar CICD
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Npm and Go and Docker build
    runs-on: ubuntu-latest
    steps:
      - name: "checkout go"
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Check go.sum exists
        run: |
          if [ ! -f go.sum ]; then
            echo "go.sum does not exist."
            exit 1
          fi
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./…
      - name: "manifest"
        run:  echo `git log | grep commit | head -1 | cut -d" " -f2` > manifest
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          context: "./"
          image: kubestar/security-webhook
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: Dockerfile
          tag: "v1.0.4"
